name: Pull Request Meta

on: 
  pull_request: 
    branches:
    - '**'

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: make online url file
        run: |
          echo "I am a banana"
